# These are supported funding model platforms

github: lyy289065406
patreon: # Replace with a single Patreon username
open_collective: re0-web
ko_fi: exppoc
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: [ 'https://lyy289065406.github.io/sponsor/' ]
