# 手动翻译 + mdBook 构建
name: Manual Translation

on:
  workflow_dispatch:
    inputs:
      raw_filepath:
        description: '待翻译的文件路径'
        required: true
        default: './gitbook/markdown/ch/chapter999/ex/00.md'
        type: string
      raw_dirpath:
        description: '待翻译的目录路径'
        required: true
        default: './gitbook/markdown/ch/chapter999/ex'
        type: string

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Git Information
        run: |-
          git config --global user.name "${{ vars._GIT_USER }}"
          git config --global user.email "${{ vars._GIT_MAIL }}"

      - name: Setup Deploy Private Key
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure pip caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Translate
        run: |-
          python ./py/translate.py -g "${{ secrets.GPT_KEY }}" -t "${{ github.event.inputs.raw_filepath }}" -d "${{ github.event.inputs.raw_dirpath }}"

      - name: Build mdBook
        run: |-
          has_update=`git diff | wc -w | awk '{print $1}'`
          if [ "${has_update}" != "0" ]; then
            ./bin/build-mdbook.sh
          fi

      - name: Commit and push (if changed)
        run: |-
          git add -A
          git commit -m "Manual translation & mdBook build by Github Bot" || exit 0
          git push origin master
